apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv 
  namespace: default
  labels:
    type: local
    label-name: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /.data/pgsql
