apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pv }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    type: local
    label-name: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.path }}
